### ISSUE TITLE
Terms of Use/Privacy Policy Agreement

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#10]
This page should be displayed after the user clicks the "Sign Up" button on the "Sign Up" page to create an account. Once the user submits his/her account info, this page is displayed to tell the user to agree to the terms of use and privacy policy. 

This page is styled similarly to the "Log In" page (#7)
* It will have a grey box styled the same way as the "Log in" page.
* Text at the top of the box should read "Terms of Use and Privacy Policy"
* Below that text, there should be some text that reads "By signing up, you agree to our Terms of Use and Privacy Policy." The words "Terms of Use" and "Privacy Policy" should contain links to the respective documents.
* At the bottom, there should be two buttons, styled the same way as the login page. One should say "Agree" and the other should say "Disagree"
* Clicking "Agree" completes the sign-up process and creates the user's account. It should redirect the user to the first page of the palm-reading process.
* Clicking "Disagree" cancels the sign-up process and redirects the user back to the homepage

A template for the terms of use can be generated using: https://www.termsfeed.com/blog/sample-terms-of-use-template/. We should read it afterwards and decide if we want to add/remove anything. 

A template for the privacy policy can be generated using: https://www.privacy-policy-template.com/. Again, we need to read it to verify that it is what we want.

Unit tests:
* check that the links to Terms of Use and Privacy Policy go to the correct pages
* Check that clicking "Agree" completes the account creation process (creates the user's account, redirects user to the right page)
* Check that clicking "Disagree" does not create the user's account and redirects the user to the right page.

**Comment by fnriv** [comment]
can we close this? doesn't look like we're doing a login so i think we don't need it?

**Comment by nsyousef** [comment]
I think we can close this. If anyone thinks we still need it, feel free to reopen it.
