### ISSUE TITLE
Design discuss 

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#11]
Based on our sketch, and what Malcolm recommends about saving chatlog (like chatGPT), we could build a chatbot design. I think the **UX/UI** of a chatbot is much better than a traditional website like this.

Updated #1: Current [Figma file](https://www.figma.com/file/baHcz99UEOscS9AGL6Szx2/Palm-Reading?type=design&node-id=0-1&t=Ua0JSJI1DIxffsFm-0)

## On your sketch:
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/59ec3c4a-34e6-4093-b0a3-950e8e0c86ba)

_Problem with our current website idea_
- UX/UI:
    - Log in/out and sign up: they usually go together as a group button in the web context, not on both sides.
    - Call to action buttons are on the right; and images are better on the left. ([Reading flow](https://www.smashingmagazine.com/2015/04/design-principles-compositional-flow-and-rhythm/))

- Functionality:
    - I suggest we remove the sign up/in functions (I don't think we have this from the start) from our app because they are not essential for its main purpose (palm reading) and they require a lot of work to implement and maintain ( need #3, #9, and #7). 
        - We don’t need them since we don’t have a comment system or a subscription system, which would also take too much time to build for a 4-week project.
        - The sign up/in functions we have now are UD (in CURD), but we don’t have an admin page to manage users anyway. I think this function is unnecessary.

## My ideas:

Simplify it as a chatbot-like, so we can have the history log function, which will solve all the CURD problems (create log, update title, read for most of the functions, and delete the conversation) on our app.

This image, for example, the title on top "Anh's fortune", during the conversation, the bot sends a palm image and guiding step, suggestion for each step could be pill badges with `(next)` `(<some pre-prep question>)`
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/5ec0ffd9-ea31-483a-a623-c7d63fffbd52)

So later on we can expand the project by implementing voice-to-action (...) if we have time

![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/fe13c21c-1a21-43b0-b122-31938363bbfe)

**Comment by lemangomeister** [comment]
> Sounds good, Faith. Badged at the bottom is a better choice regarding the freq of touching points. We can have other options like buttons under the images if needed.
> 
> ![facebook-messenger-bots-12-620x791 png copy](https://user-images.githubusercontent.com/9192184/238113160-e48de2e2-1dca-4500-bdfe-36d212e13560.jpg)
> 
> ![image](https://user-images.githubusercontent.com/9192184/238113197-6b0ce6b7-395e-4463-a08f-9f7022cc5905.png)

These images don't appear for me. Anyone else just see blue text instead of images? Clicking on them gives an error

**Comment by phuanh004** [comment]
Hmm probably, when @henryzhang03 changed the repo from private to public, it causes this image error.
