### ISSUE TITLE
create palm reading script

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#16]
create script with different responses based on the different attributes on palm reading. contributes to #15 

tasks:
on miro: 
- [x]  research and organize different significances of lines. put this on board
- [x] create a flowchart of planned script

off miro, and on a relevant file? not sure how we'd store this data, maybe in a json file? need help deciding

- [ ] create script that can be accessed on chatbox

**Comment by lemangomeister** [comment]
Too many choices to write a specific script for each choice so I just made a simple example from ChatGPT. Will cater to each choice or figure something easier when I get the chance.
