### ISSUE TITLE
chatbox crud functionality

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#17]
adding this as base; but basically be able to save chats on a sidebar and rename the conversations (like chatgpt ui)
this is important for #15

**Comment by fnriv** [comment]
- [ ] save session to storage
- [ ] renaming sessions
- [ ] delete session
- [ ] bring session back up to screen

**Comment by phuanh004** [comment]
Let's see what would be the name of the local storage
