### ISSUE TITLE
create adrs

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#18]
- [x] schedule a 15 min meeting for everyone to approve this week

adrs (just quick writeups like how malcolm showed us) for: 

- [x] summary of project (you can refer to pitch)
- [x] what we define "done" as for an issue
- [x] decided tools for development
- [x] build path #14 
- [x] documentation template- collaborate with whoever does #13 
- [x] testing procedures

**Comment by henryzhang03** [comment]
will discuss ADR for naming files in next meeting
