### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#2]
In the footer of the site, I would like to put a disclaimer that says the following:

DISCLAIMER: This app was written as part of a school assignment. The content of this app and the practice of palm reading are not endorsed or affirmed by all the developers.

The disclaimer should be centered in the footer and should be in font size 13pt.

I am open to discussion about the content and styling of the disclaimer if anyone disagrees with what I have proposed.

**Comment by fnriv** [comment]
do we still want to do this? maybe as like an intro animation upon first opening the page

**Comment by nsyousef** [comment]
Yes, I would still like to do this. I would be fine with having it as an intro animation. Or if you want, we could have a banner at the top or bottom of the page with an 'x' in the corner to close it (sort of like a cookie banner).

**Comment by nsyousef** [comment]
I can take care of creating this feature if you want. Has there been any discussion on creating the design for the intro animation? I can collaborate with you all on how that is working and see how we can integrate this. Or if it is better to just make this a closable banner at the top or bottom of the page, we can do that too.

**Comment by phuanh004** [comment]
> I can take care of creating this feature if you want. Has there been any discussion on creating the design for the intro animation? I can collaborate with you all on how that is working and see how we can integrate this. Or if it is better to just make this a closable banner at the top or bottom of the page, we can do that too.

Since the popup is annoying, it usually uses to limit actions (e.g. show ads, subscribe) or either prevent the users from making mistakes (e.g. delete action). Therefore, I think there are 2 other approaches to this:
- Show on the chat as an incoming message
- Have a link on footer to the disclaimer page

What do you think?

**Comment by nsyousef** [comment]
Do we still need this open? The disclaimer is in the app now, but not sure if we want to use this issue to discuss any changes to make to it. I was talking with @phuanh004 in lecture and he said he wanted to perhaps put the disclaimer below the chat box in the footer of the page. I know Professor Powell also suggested we perhaps make it so that the disclaimer message is a different color or has some distinction so it doesn't look like Simba sent it. Did we want to do either of these suggestions or just keep it how it is. I would be fine either way as long as the disclaimer is present.

**Comment by henryzhang03** [comment]
@phuanh004 if you can put it in a footer somewhere that would be great, otherwise, I can handle changing the color of the text. Let me know.

**Comment by phuanh004** [comment]
@henryzhang03 probably just the footer like chat GPT:

Probably keep it short like:
- For school purposes only. Palm reading is not endorsed by creators.

How does it sound like?

Example:
![Screenshot 2023-06-07 at 7 40 51 PM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/e989d10e-2f17-48b4-9d26-646c5ed0e37d)

**Comment by henryzhang03** [comment]
@phuanh004 yea that looks good

**Comment by phuanh004** [comment]
Done
