### ISSUE TITLE
UI chatbox and message

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#20]
- [x] Add file button
- [x] Text input
- [x] Send message button
- [x] Conversation bubbles
    - [x] Shadow DOM for the reader and user
- [x] #22
- [x] Chat - Group of options

**Comment by phuanh004** [comment]
There is a missing function of having a chat option group. So, I reopen this. Thank you @dolivares11 for pointing it out 😬!

**Comment by Christby** [comment]
I've implemented some basic functionalities of the chat option group without styles, still trying to figure out how to put the content of selected button as the next user input text

**Comment by dolivares11** [comment]
I'm pretty much done implementing the chat option groups without the styling as well. I've gotten it to walk through a whole conversation of one palm line ex. the heartline.
