### ISSUE TITLE
Add fonts

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#22]
#20 

Can someone who makes the Figma file also add the font you are using to the website?

**Comment by ChayPark** [comment]
I have a PA due tonight, so I can work on this part at midnight.

**Comment by ChayPark** [comment]
I added the font to our code and fixed the color because black is quite dark, so I changed the background to a brighter color. I have pushed these changes to the chat branch.

**Comment by phuanh004** [comment]
Thank you @ChayPark, looks good. I changed some chat colors to match your light theme.
