### ISSUE TITLE
User Mistakes - Chat Reversibility

### ISSUE THREAD

**Issue by henryzhang03** [cse110-sp23-group3/cse110-sp23-group3#24]
If a user makes a misclick for their input, we want to be able to offer an option on every question to change the answer to the previous question.

Implementation-wise, I'd say you can delete the last element from the array of determined fortunes, and just UI go back to asking the previous question. Probably also need to store the previous question if it is custom and not generic for everyone.

**Comment by phuanh004** [comment]
Can we have a wireframe to where the `go back` button should be?

**Comment by Christby** [comment]
Just to confirm if I am supposed to create a branch from v2.0.0 to implement this functionality

**Comment by Christby** [comment]
Are we still considering to implement this function? I just thought about this and I feels that this functionality is not necessary because we just directly outputs the fortune based on the user input instead of following a long script that talks about several parts of the palm lines.

**Comment by henryzhang03** [comment]
Maybe we can let them edit their last description @Christby

**Comment by Christby** [comment]
What is the latest version that I should create a branch from? @henryzhang03

**Comment by henryzhang03** [comment]
@Christby probably history-crud-functionality
