### ISSUE TITLE
Custom Dialogue Integration

### ISSUE THREAD

**Issue by henryzhang03** [cse110-sp23-group3/cse110-sp23-group3#25]
Currently, our chat asks a series of hardcoded questions. For example, Q1 might be "Do you have the sun line", but then Q2 from our site won't use the response from the user for what Q2 should be. If I answer "yes" to Q1, I still get "Do you have the moon line", not "Blah blah blah, do you have the moon line". Let's make it more personal and interactive instead of a questionnaire by incorporating responses into our website's dialogue.

Possible implementation features that I think might be very cool is to create an AI api key and incorporate the response from the AI into our dialogue. For example, if user says "yes" to "Do you have the sun line", we call the AI API saying "I have the sun line, what does this mean", then take the response from the API, append it to the beginning of the next string before asking "Do you have the moon line".

**Comment by phuanh004** [comment]
1. We will go for the local first, so I'd say using js to find keyword the `.includes`, which should implement in #26 #17, or whatever is related, not the UI one on #23.
2. Do you have any AI suggestions? I suggested Open AI before but I think we don't want to pay for this.

**Comment by henryzhang03** [comment]
I made a separate issue for the API we will call for our responses. @phuanh004

**Comment by henryzhang03** [comment]
@phuanh004 or any dev, if you'd like to start implementation, please refer to: https://github.com/cse110-sp23-group3/AI-API. BTW, the api is slow by default because openai is pretty slow. But, in prompts, please say "limit your response to 1 sentence", avg. of 2-3 seconds response so maybe add loading animation while you wait for the response.
