### ISSUE TITLE
Bug on Dylan's branch

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#27]
```sh
Properties of undefined (setting 'disabled')
    at HTMLButtonElement.<anonymous> (index.html:253:47)
```

![Screenshot 2023-05-28 at 2 57 14 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/19c044d3-9ad4-46f0-9fa8-6cb2b32feb1a)

**Comment by Christby** [comment]
Can you explain what is the bug of here? I can take care of this if nobody else is doing this

**Comment by phuanh004** [comment]
Follow the sequence on the image on the step and it will have the error message on the Devtools console.

**Comment by Christby** [comment]
I think this is probably just an index issue where i is set to be equal to choicesButton.length at the last iteration of the for loop. I've fixed it and separated the script tag into a js file in the source/scripts folder.

**Comment by phuanh004** [comment]
Please commit with the issue tag if you fix it so ppl can have the reference later

**Comment by dolivares11** [comment]
I was able to fix this, and will be pushing a fix soon.
