### ISSUE TITLE
Discuss revamping theme: Lion King Style 

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#30]
I think we need to circle back to some of our user stories for our product:
<img width="982" alt="Screenshot 2023-05-30 at 12 13 10 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/103224896/db7cc042-4fd1-4f05-88f7-30dfda879a6d">

Ricky's user story is the most important. Let's try to add some animation/themes/etc to match the lion king theme we pitched.

Refer to #21 for links previous wireframe, etc

tasks regarding this (can form into issues as discussion continues)

- [ ] choosing if we need to create a persona for the palm reader
- [ ] add lion king animation at beginning? #6 
- [ ] choose photos to add to page

**Comment by fnriv** [comment]
i started some brainstorming on colors/themes on the [miro board](https://miro.com/app/board/uXjVMN1qypo=/)

**Comment by fnriv** [comment]
tasks regarding this (can form into issues as discussion continues)

- [ ] choosing if we need to create a persona for the palm reader
- [ ] add lion king animation at beginning? #6 
- [ ] choose photos to add to page

**Comment by phuanh004** [comment]
@fnriv Hey Faith, can you move and update the task list on `#1` in this issue, so that we can create and issue from the tasks?

**Comment by fnriv** [comment]
@phuanh004 updated!

**Comment by MichaelYe48** [comment]
@fnriv what sort of animation are you looking for? Will this be like a CSS transition?

**Comment by henryzhang03** [comment]
@phuanh004 closed this above^
