### ISSUE TITLE
About us page?

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#31]
I think it'd be cute to write a little quip about ourselves? Just an extra page, we can put a photo of ourselves and maybe a little lion king character and a quip. would love some opinions on it, i think it'd be easy enough to implement (as there is no interaction you'd just have to be able to go back to the palm reading section)

**Comment by nsyousef** [comment]
I would be fine with it. I would be willing to implement this. Would just people to send me their info.

**Comment by dolivares11** [comment]
Yeah, this sounds like a good idea. It's easy, and is a nice way to credit ourselves

**Comment by fnriv** [comment]
what info do you need nick?
ie name, photo, major college fun fact?

**Comment by nsyousef** [comment]
I was thinking we could have profile-style photos, names, and people could write a short 2-3 sentences about themselves. You can include things like name, major, college, fun fact, interests, career goals, and anything else you want to share. I was thinking of making it look something like the image below (this is a very rough sketch; I am open to design suggestions).

![Screenshot 2023-06-01 at 12 08 10 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/46a657fd-3f5a-4bb6-a096-cd34e4fbee43)

I would probably just copy-paste whatever people want to say about themselves in and possibly make minor edits for consistency if needed.

**Comment by nsyousef** [comment]
Here is a more fleshed out version of what I am envisioning for the about page. Please let me know what you think before I code it up.
![Screenshot 2023-06-01 at 1 15 57 AM](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/effa0d77-330d-44a0-ae64-d677985966c3)

To navigate to this page, the user would click "About Us" on the main chat page. He or she would then be taken to this page. To get back to the chat, the user could use the browser back button or he or she could click the "< Back to Chats" link on this page. 

This design is on the Figma, along with an alternative design that I made. Let me know which one you prefer or if you have any feedback about these designs.

**Comment by fnriv** [comment]
I do have a suggestion? just for the readability; we can separate name and role like this (i make a separate frame next to your prototype

<img width="564" alt="Screenshot 2023-06-03 at 12 28 27 AM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/103224896/78328e1d-572d-4d5d-b03e-b09c48bfe35e">

**Comment by nsyousef** [comment]
Sure. We can do that.

**Comment by fnriv** [comment]
I think from here I propose the following tasks @nsyousef ; if you are fine with it feel free to go ahead and contact everyone via slack unless someone gives opinions otherwise by tomorrow morning

- [ ] collect info (have everyone dm you a photo and description
- description: 2-3 sentences including name, major, favorite animal, and an fact about them
- [ ] create page with profiles
- [ ] connect page to regular interface with buttons and side bar

**Comment by nsyousef** [comment]
Sounds good. Will send out an announcement on Slack about it now to give people enough notice (since I will probably be busy tomorrow morning).

**Comment by henryzhang03** [comment]
closed with recent merge
