### ISSUE TITLE
Chat bubble animation

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#41]
Profile photo with the chat bubble animation would be cool to implement too:
E.g. https://codepen.io/organicrabbit629/pen/bGmPEoe

**Comment by ChayPark** [comment]
I implemented the animation, pushed it into the 'bubble' branch, and added the Simba image for incoming messages.

**Comment by ChayPark** [comment]
If anyone reviews my branch, let me know! I can merge my work into the main branch and close the issue.

**Comment by phuanh004** [comment]
@ChayPark just open a pull request to the `v2.0.0` branch then we review it!

**Comment by phuanh004** [comment]
@ChayPark I already pick your photo and add the change to `v2.0.0`

See:
#42
