### ISSUE TITLE
Github page for our webpage

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#50]
Right now our webpage is pointed to the `README` of the `root` folder on `main`. 
Related issue: #32.

So the task would be to point it to our actual product:
- [ ] Our `main` page
- [ ] Our `v2.0.0` branch
- [ ] Add it to the `README.md` #43

**Comment by lemangomeister** [comment]
Can you clarify further? I don't understand this issue at all

**Comment by phuanh004** [comment]
https://cse110-sp23-group3.github.io/cse110-sp23-group3/ is pointed to the README but, it could be fixed with #43. But it is just in the `main`.

I think we are also need another gh-page for `v.2.0.0` on that branch as well, so people can take a quick look on that (related to CI/CD, gh action)

**Comment by lemangomeister** [comment]
Are you saying the link should be showing the palm reading app instead of our README?

**Comment by phuanh004** [comment]
Yes, read the conversation in the PR

**Comment by lemangomeister** [comment]
Can you educate me some more about this? Based on what I've [read](https://github.com/orgs/community/discussions/23073), deploying Pages from a branch only gives two options. What is wrong with having the source (index.html?) be in the /docs folder?
