### ISSUE TITLE
Create Trash Can delete button

### ISSUE THREAD

**Issue by henryzhang03** [cse110-sp23-group3/cse110-sp23-group3#53]
I made a `deleteFromHistory` function in the history-crud-function branch, just need someone to make the HTML and CSS for a trash can that when the button is clicked, it calls deleteFromHistory.

**Comment by nsyousef** [comment]
I can do that. I will just add it to the history-crud-function branch.

**Comment by nsyousef** [comment]
What needs to happen when the delete button is clicked? Right now, I have it call `deleteFromHistory(key)` where key is the key of the conversation to delete, call `saveToHistory(currentSession)`, and `deleteHistoryButton` (a function I wrote to remove the history button and delete button from the DOM). Is there anything else I need to do? And should I be calling `saveToHistory(currentSession)` or should I just leave that be for now?

**Comment by fnriv** [comment]
do you need me to find / form a trash can button? or are we just going to use text button

**Comment by nsyousef** [comment]
I already put in an icon from online, but we can change it if you want. It would be a simple matter of changing the file and a single filename in a constant in the JS. I have committed what I have now to the `history-crud-function` branch so you can look at it and see. The buttons themselves are fairly basically styled right now. I can style them if you want, although if we are going to revamp the theme it might be better to just do it when we put in the styles for the new theme.

**Comment by lemangomeister** [comment]
Should this be closed now ?

**Comment by nsyousef** [comment]
Confirm with @henryzhang03 to be sure, but I have done the task he said above (created the HTML and CSS for the button, as well as added some JavaScript so it appears and disappears). And it calls the `deleteFromHistory()` function as Henry asked for. Kind of waiting for Henry to answer my question above as to whether he wants me to do anything else with it. I would say leave it open for now.

**Comment by henryzhang03** [comment]
We need to fix a lot of things related to the functionality @lemangomeister @nsyousef , for now, let's keep this issue open, it wont be a hard one to close once the main functionality is bullet proof
