### ISSUE TITLE
Random operation causes problems

### ISSUE THREAD

**Issue by Christby** [cse110-sp23-group3/cse110-sp23-group3#57]
I tried some input on the new history-crud-function and found that there are some problems occur when I don't follow the whole process of input messages or button choices. When I clicked any palm line button and the window is waiting for my input of description for the palm line, I quit and start another chat. Then a lot of errors might occur. Here are some examples of problems that happens to me when I'm testing it.
<img width="1440" alt="Screenshot 2023-06-03 at 15 25 08" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/97484108/c9b14e13-abf6-4e86-a491-5c9a65400f76">
<img width="1440" alt="Screenshot 2023-06-03 at 15 25 24" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/97484108/5afc1ed7-3a98-40c4-957f-505c41a7c402">

**Comment by henryzhang03** [comment]
no longer relevant
