### ISSUE TITLE
Error on comparing chat options in lowercase

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#61]
@lemangomeister,
Please change the chat script on the crud branch or this branch to make sure it does not cause the error when merging 
Your commit on https://github.com/cse110-sp23-group3/cse110-sp23-group3/commit/427082d7f50b1c3232cfba5d23e06e82812be68d caused the conflict when comparing the choice with the hard coded lowercase choices options.

Probably suggest change all the comparing `===` to `includes`

**Comment by lemangomeister** [comment]
@phuanh004 
![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/69333304/9319c1b5-1bad-4925-872b-f2e032804e47)
`buttonChoice` doesn't seem to have an `includes` function

**Comment by henryzhang03** [comment]
fixed in newest update
