### ISSUE TITLE
OverallFortune Persists

### ISSUE THREAD

**Issue by henryzhang03** [cse110-sp23-group3/cse110-sp23-group3#74]
The user's overall fortune persists across multiple chats, so if I get a reading for my Heart Line in one chat, then my Fate Line in another, it will print both in the second chat

**Comment by Christby** [comment]
@henryzhang03 Maybe we should reset all variables to their initial state when a new chat is created

**Comment by henryzhang03** [comment]
@Christby exactly my thoughts, just fixed
