### ISSUE TITLE
add palm diagrams for hands

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#80]
this is to make it easier for user to identify lines.

do we need one for each line and like diagrams for description of lines?

**Comment by Christby** [comment]
Maybe we can show the image of a hand with highlighting on the chosen palm line from the users. 
Or we can display this image at the beginning of a new chat.
![palm lines](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/97484108/8647cfc1-3633-4515-8fcf-f43eb6963383)

Which one do you think is better?

**Comment by phuanh004** [comment]
That image does not fit the UI. Find something like the image below or design one.
Find a better one than just a random raw image like that or it will break the whole thing

![image](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/9192184/53b8d974-7a9c-496b-9fae-3db27367c379)

**Comment by phuanh004** [comment]
It's the best if we can have one image for each step

**Comment by Christby** [comment]
@phuanh004 Do you think that this will work? I can draw the palm lines and add texts on it
<img width="329" alt="Screenshot 2023-06-08 at 15 33 12" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/97484108/f59f5b81-d836-4d86-8e50-fba0b6825717">

**Comment by Christby** [comment]
Or this one?
<img width="728" alt="Screenshot 2023-06-08 at 15 39 34" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/97484108/d01d7acb-2a4a-4dfe-b9d6-03401aa2843f">

**Comment by Christby** [comment]
@phuanh004 @fnriv What's your opinion?

**Comment by phuanh004** [comment]
Can you make 2 versions so I can compare? But both look good

**Comment by Christby** [comment]
@phuanh004 It's done on the branch add-diagram. I didn't change the style much because I don't want to mess with other styles. The images are added in line 56 & 57 of main.js and the addImageToChat function is implemented at the end of main.js.

**Comment by Christby** [comment]
Personally I prefer the first one

> @phuanh004 Do you think that this will work? I can draw the palm lines and add texts on it <img alt="Screenshot 2023-06-08 at 15 33 12" width="329" src="https://user-images.githubusercontent.com/97484108/244525541-f59f5b81-d836-4d86-8e50-fba0b6825717.png">

**Comment by phuanh004** [comment]
Yes, a vector file will be better, or either png without the background.

**Comment by fnriv** [comment]
the first one seems fine? definitely gives a more playful/comical feel though if we are aiming for that vibe, so if we are looking for slightly more elegant then i think one that's slightly more realistic in terms of hand shape would be better

**Comment by Christby** [comment]
> Yes, a vector file will be better, or either png without the background.
> 
> Having them in both dark/light modes would be cooler

What is a vector file?
I'm not sure if we can delete the background since there are texts in the background

**Comment by phuanh004** [comment]
https://www.youtube.com/watch?v=YGBIc6oJCos

**Comment by yujiaen1999** [comment]
![WechatIMG11](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/a1aa85df-75bb-45bd-857e-6f16bd5100fe)

Here I have a png without the background. Do you think this works? @phuanh004 

We can draw all palm lines and highlight the line which we are going to read.

**Comment by phuanh004** [comment]
Looks good!

**Comment by yujiaen1999** [comment]
![IMG_6395](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/47964649/4a653aab-cf98-439b-bf18-1f7d9fa72fd0)

**Comment by Christby** [comment]
@phuanh004 Latest update committed

**Comment by ChayPark** [comment]
I don't know if it's too late, but I also created a physical hand version because it is difficult to determine the location of the palm lines in some pictures
![_com apple Pasteboard CHKJlc](https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/99235173/c6ecb5b6-7075-4ac8-89fc-6f04e127d4b9)

**Comment by Christby** [comment]
@phuanh004 @henryzhang03 Can you check if you are satisfied with the current display of the palm diagram? If you think it works, I can make the pull request

**Comment by henryzhang03** [comment]
resolved, in prod now.
