### ISSUE TITLE
CI/CD: Cache npm install process

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/cse110-sp23-group3#81]
The packages are installed every time, and need to cache.

**Comment by phuanh004** [comment]
@henryzhang03 #125 still uses 25s to install dependencies

**Comment by henryzhang03** [comment]
@phuanh004 yea I mean I think it needs it? Not sure how to cache because each time we use a different instance

**Comment by phuanh004** [comment]
Keep this open I will take a look at it later tonight

**Comment by henryzhang03** [comment]
@phuanh004 just tried so many things but still isnt working, not sure why but gonna try again on it tmrw

**Comment by phuanh004** [comment]
@henryzhang03 I just checked, we have too many dependencies, so that's probably why
