### ISSUE TITLE
CSS Not Loading in Live Deployment

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#82]
Some of our CSS files are not loading in the live deployment of the site. Here is what it looks like when I try to access it from the link on the README in `main`:

<img width="1792" alt="Screenshot 2023-06-08 at 4 06 13 PM" src="https://github.com/cse110-sp23-group3/cse110-sp23-group3/assets/114201888/c49c9b81-52b1-4d51-8f92-18c620d672be">

**Comment by henryzhang03** [comment]
fixed @nsyousef
