### ISSUE TITLE
Convenient Result Display

### ISSUE THREAD

**Issue by MichaelYe48** [cse110-sp23-group3/cse110-sp23-group3#83]
Right now when the user clicks the button to have their palm reading results displayed, they have to scroll to the bottom to read it. A QOL fix would be to automatically scroll down to the result in a manner similar to how the chat already moves to accommodate questions prompted to the user.

**Comment by Christby** [comment]
I don't know why this happens since we have the scroll to bottom function in addMessageToChat, but I just fixed this in add-button branch

**Comment by henryzhang03** [comment]
done with @Christby commit [de94fee](https://github.com/cse110-sp23-group3/cse110-sp23-group3/commit/de94fee8a00b28f683d54378f96ca99a6eb82e68)
