### ISSUE TITLE
Remove settings button from sidebar

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#86]
The settings button in the sidebar does not seem to do anything. We should probably remove it since it has no functionality. I don't think there will be enough time at this point to add functionality to it.

**Comment by MichaelYe48** [comment]
That is true. If using the toggle counts as CRUD we can probably skip the settings button functionality

**Comment by dolivares11** [comment]
Yeah, probably best to remove it since we also have to finalize our code soon, so I don't think we will be adding anything new to it.
