### ISSUE TITLE
Documentation out of date in main.js (and possibly other files)

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#88]
While writing unit tests, I have noticed a lot of function headers that seem to be out of sync with the actual code of the functions. For instance, the function headers may be missing parameters. There are also some function headers which list the wrong datatype of the parameters. I have noticed this in `main.js` and I am not sure if it is also the case in other files. I don't know the full extent of what is out of date, but we might want to go through and double-check our JSDoc documentation to make sure it is consistent with our code.

**Comment by MichaelYe48** [comment]
The function headers for rebuildChat, createHistoryButton in main.js for example ^.

**Comment by fnriv** [comment]
@MichaelYe48 are you saying those are out of date ? or those are fine

**Comment by MichaelYe48** [comment]
Those functions headers I mentioned are erroneous.

**Comment by henryzhang03** [comment]
completed.
