### ISSUE TITLE
When a user accesses saved chats, images do not show up.

### ISSUE THREAD

**Issue by nsyousef** [cse110-sp23-group3/cse110-sp23-group3#89]
Steps to reproduce:
1) create a chat and go through the palm reading process
2) create a new chat and go through the palm reading process
3) go back to the first chat you made by clicking it in the sidebar. The images no longer show up in that chat.

I discovered this bug while I was testing. I think it is because the `rebuildChat` function does not have any way to handle adding images to the chat. If there is an image in the saved chat history, it just skips over the image.

**Comment by Christby** [comment]
I assumed that we don't need the images when rebuilding the chat since displaying the image is to help users know which palm line they should observe and describe for themselves. Adding those images when rebuilding the chat would increase the loading time unnecessarily. How do you think?

**Comment by nsyousef** [comment]
Oh ok. That is a good point. Given the time crunch that we are on, it is perhaps better not to add that feature if the app was originally designed not to have it. I originally just thought it was a mistake which is why I brought it up, but if it was a purposeful choice we can just leave it as is.

**Comment by nsyousef** [comment]
Closing this issue.
