### ISSUE TITLE
Public Vid: Product Demo

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#92]
Create video showing off our product! Video should probably be no more than 2 minutes.
If you are good at showing off/presenting would love to have you record :D let's make this snazzy

Tasks

- [x] Assign demo recorder
- [x] Create list of features we want to show off
- [x] Record video and send to Faith

**Comment by fnriv** [comment]
@henryzhang03 i believe you volunteered to do this ? lmk if you want to pass it to someone else though

**Comment by henryzhang03** [comment]
I'm doing it now @fnriv
