### ISSUE TITLE
Public Vid: Retrospective

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#93]
**Send to faith by monday, 11:59pm**
Need 2 people NOT doing another part of the public video to make a video with no more than 20-25 seconds:

- what challenges you faced
- what things you felt you overcame 
- anything you feel you would do differently now that you are done

**Requirements**
- No need to introduce yourself
- horizontal video of you talking
- no more than 20-25 seconds

Tasks
- [x] Assign video to 2 people during meeting tomorrow
- [x] record videos
- [x] send video to faith by monday 11:59 pm

**Comment by Christby** [comment]
@fnriv Did you say in the meeting yesterday that you will also be doing this video?

**Comment by fnriv** [comment]
i was planning on to yes; but if you think 2 is enough then im down for that. i'm editing the videos as well

**Comment by Christby** [comment]
Do you have a planning about what we will be talking about? I'm currently planning to have about 15s for the first two parts and 10s for the third part. However there are things we need to discuss like how many challenges and how many overcame challenges should we talk about given the time constraint.

**Comment by MichaelYe48** [comment]
What challenges did you have in mind @Christby ? If there are multiple we can probably split them up

**Comment by Christby** [comment]
@MichaelYe48 I think that one of us can talk about challenges and overcame challenges, the other can talk about things we will do differently. Which one do you want to talk about? I think that we can do this without @fnriv to reduce her workload if she agrees to it.

**Comment by MichaelYe48** [comment]
I'm not too sure if the videos are 20-25 seconds each or just 1 video that is 20-25. But if it's just 1 video we can do what you're proposing. What challenge do you want to do? I was thinking about how midterms really restricted how much time we had to do projects, but we can also do whatever you had in mind.

**Comment by fnriv** [comment]
each video should be at most 20-25/
if you all want to split it between you two that would be great, that way i can focus on editing later

**Comment by Christby** [comment]
@MichaelYe48 Here's my thought: One challenge is that the communication between us was restricted by distinct schedules and heavy workload for other classes so that it's hard to find a relatively long period of time when everyone can be 100% focus on the project. However, we overcame this challenge by being considerate to other people's difficulty and taking responsibility of doing heavy works in turn so that everyone made significant contribution when they have time. We did this by keeping clear documentation about what we do so that people who takes over will know exactly what to do next instead of wasting a lot of time on communications.

**Comment by Christby** [comment]
For the things we might do differently, I am thinking about things like adding a home page, adding more Lion King characters, improve on the way of displaying chatbox ...

**Comment by Christby** [comment]
@fnriv Are we supposed to record our parts separately or record the video together, probably in zoom?

**Comment by MichaelYe48** [comment]
Chris I think we probably can record two different videos if each is suppose to be 20-25 seconds long. The challenge I will probably do is juggling varying levels of expertise between group members.

**Comment by Christby** [comment]
I'm still confused. 20-25 seconds is for the length of the whole video or we should both record a 20-25 seconds long video separately?

**Comment by MichaelYe48** [comment]
Faith said that each video should be at most 20-25 seconds

**Comment by Christby** [comment]
Oh, so we should each talk about the 3 parts of this video for about 20-25 seconds?

**Comment by MichaelYe48** [comment]
Yea we probably can. You can do what you outlined above and I'll do challenge I mentioned earlier.

**Comment by Christby** [comment]
Just to confirm, each of us will talk about one challenge and how we overcame it, also we will mention some things we feel that we will do differently

**Comment by fnriv** [comment]
yes that is correct. your personal vid should be 20 to 25 seconds

**Comment by fnriv** [comment]
@MichaelYe48 @Christby both of your videos look great!
i might add a video to tie your points together and add a bit more about improving the product

**Comment by fnriv** [comment]
https://youtu.be/jSKOH-n8YdU
finished link!

**Comment by phuanh004** [comment]
Check slack
