### ISSUE TITLE
Public Vid: advice for future 110 students

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#94]
**Send to faith by monday, 11:59pm**
Need 3 people **_NOT_** doing another part of the public video to make a video with no more than 20 seconds with a piece of advice for future powell 110 students on how they can crush the project.

**Requirements**

- No need to introduce yourself
- horizontal video of you talking
- no more than 20 seconds
- be inviting/energetic!

Tasks

- [x]  Assign video to 3 people during meeting tomorrow

expecting video submissions from:
- [x] jiaen
- [x] mico
- [x] nick

**Comment by fnriv** [comment]
Maybe we can have a lead, dev, either designer or planner speak to get different role perspectives

**Comment by yujiaen1999** [comment]
Self assigned to #94

It will be a 20 seconds advice video, and each of us can do a few seconds video with brief self-intro and advice from our role. Then combine them together.
