### ISSUE TITLE
Private Vid: Repo tour

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#95]
"_A video discussion about how to access your repo, a tour of the repo organization and a demonstration of making a small change to the repo and the completion of the build process.  You may need to write more detailed discussion of building or onboarding the product than the video supports.  If so create a markdown file called "onboard.md" and put it in your documentation which goes into more details._"

@henryzhang03 or @phuanh004 or others; let's discuss on how we want to do this for the private video. i think this part can be 2-5 minutes?

**Comment by henryzhang03** [comment]
I can do this, no worries. It should not be too difficult.
