### ISSUE TITLE
Private Vid: Agile Practices

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#96]
"_A more involved retrospective about how your Agile practices were conducted and what challenges and victories the team faced.  Honesty is the best course of action here as we are more likely to be lenient if we understand you are aware of what you didn't do well on the project and practices._ "

Would like leads to speak on this as well as 1-2 people not already in the private video.
**Requirements**
- horizontal video of you talking 
- not sure about video length; need to plan that still

Tasks (as of now)
- [x]  assign video talkers (1-2 non leads)
- [x]  finalize points of discussion by **monday midnight**
- [x]  submit to faith by **tuesday 5pm**

**Comment by phuanh004** [comment]
I decided to talk about Agile product management (and Kanban if not enough time) | with Github.

**Comment by MichaelYe48** [comment]
It would be nice to know the length of the video when possible. If they are willing to be more lenient about our difficulties we should probably be more strategic in what we talk about so we can cover some weak spots.

**Comment by MichaelYe48** [comment]
Should we finalize what we say for the video?

**Comment by phuanh004** [comment]
Done
