### ISSUE TITLE
Private Vid: Next Steps Retro

### ISSUE THREAD

**Issue by fnriv** [cse110-sp23-group3/cse110-sp23-group3#97]
"_Conclude your video with a discussion of what things a team taking on your project should do next.  Discuss the features not built yet, improvements to the build pipeline or anything else you would have gotten to given another quarter worth of work.
_"

I would like 1-3 people to talk about this; @henryzhang03 maybe you can regarding build pipeline but we can discuss at meeting tomorrow

**Requirements**

- horizontal video of you talking
- not sure about video length; need to plan that still

Tasks (as of now)

- [ ]  assign video talkers (1-2 non leads)
- [ ]  finalize points of discussion here by monday midnight
- [ ]  submit to faith by tuesday 5pm

**Comment by lemangomeister** [comment]
We can probably add #72 as a talking point here.

**Comment by lemangomeister** [comment]
Working on this one
